### ISSUE TITLE
Possible unexpected behaviour due to variable type being too small

### ISSUE THREAD

**Issue by veox** [Great-Hill-Corporation/Start-Without-Me#9]
On [line 56](https://github.com/Great-Hill-Corporation/start-without-me/blob/master/src/StartWithoutMe.sol#L56), there's this:

```
  function setN(uint8 _n) isOwner {
    // to big?
    if (_n > 63)
        throw;
```

~~I'm reasonably sure this won't work as expected.~~ `_n` is a `uint8` (one byte allocated in `memory`), with values [0;~~63~~255], ~~so that conditional will never be `true`~~.

What happens when you pass, say, a `uint32` to `setN()`? Since the function signature calls for a `uint8`, only one byte will be pushed to the stack. Don't have time for proper disassembing now, so that's a guess.

Only took a glance and didn't read the docs, but this immediately stood out. The complications are probably not limited to this particular check.

**Comment by veox** [comment]
Oops! Was trying to be a smart-ass without my morning coffee. This never works.

**Comment by veox** [comment]
OTOH, if you're curious what would happen anyway, from the [Contract ABI doc](https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI):

> uint<M>: enc(X) is the big-endian encoding of X, padded on the higher-order (left) side with zero-bytes such that the length is a multiple of 32 bytes.

So, if say a `uint32` was passed with value `0x10203`, that'd be padded to `0x00010203`, and `0x00` would be at the memory location where `setN()` expects to find its `uint8`.

EDIT: I'm sure most clients guard against such deviant behaviour, and the function signature for `setN(uint32)` wouldn't exist, so the fallback would be called instead. Of course, manually constructing a transaction with "extra" data and the right function signature is possible, but that's way irrelevant.

Sorry for the spam! :space_invader:

**Comment by veox** [comment]
Finally, consider adding the `external` specifier to `setN()`.

**Comment by tjayrush** [comment]
Thanks so much for your comments. No problem with the spam. It made me think.

What does external do? Are function internal or external by default?

**Comment by veox** [comment]
They're `public`, actually. Variables are `internal`. See [docs](http://solidity.readthedocs.io/en/latest/contracts.html#visibility-and-accessors). :)
